### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by louierosero-gss** [louierosero-gss/Uluru-QA#1]
## 1. Specification / Bug

commit by each tasks below

* [x] add a css file for our client-ownself customizing, just a simple css file named customize.css with no contents inside. Our client will modify this file when he wants to customize style via WordPress dashboard
* [x] so as js, add customize.js
* [x] add [All-in-One WP Migrations](https://ja.wordpress.org/plugins/all-in-one-wp-migration/)plugin
* [ ] replace background images of service cards on top pages, I've shared images with your boss's dropbox, named "service_photo"

## 2. Screen shot

* [x]  iPad top page

|  |  |  | |
|-|-|-|-|
| ![4dc67550-edf2-4f5b-828b-56cd2429efd1](https://user-images.githubusercontent.com/5038584/37948383-ea7554ce-31ca-11e8-9952-aba857aa02e0.png)|![d638e967-4b24-41c6-b544-fc08b9b7b290](https://user-images.githubusercontent.com/5038584/37949189-8860b838-31ce-11e8-9926-fc837551cf48.png)|![592773f1-e4ea-4337-bc11-e59a4c61e322](https://user-images.githubusercontent.com/5038584/37948440-4886cd5e-31cb-11e8-80cf-2f0d9d2325d0.jpeg)|![ff1210e5-2587-43c6-a60e-2f3e5cfa6f43](https://user-images.githubusercontent.com/5038584/37948441-48b37caa-31cb-11e8-8109-8dcc84e60d9f.jpeg)|

---------------

* [x] SP top page

|  |  |  | | |
|-|-|-|-|- |
| ![d922487e-594b-47bf-8961-17d03b5613d8](https://user-images.githubusercontent.com/5038584/37948653-1b832928-31cc-11e8-8a9e-a3522176ce1d.png) | ![bd0e75e5-c33b-4422-9bf6-41c9901634c0](https://user-images.githubusercontent.com/5038584/37948711-570e94aa-31cc-11e8-9b04-f9294d707793.png) | ![bd9c3531-c4b3-4024-b833-04f8ac5109dd](https://user-images.githubusercontent.com/5038584/37948803-cedda1ec-31cc-11e8-8634-1d1a2662533c.png) | ![9c52c80b-7920-4be5-ae08-e380621d18e9](https://user-images.githubusercontent.com/5038584/37948865-11a41e8e-31cd-11e8-92b1-fb121f2c714c.png) | ![a86b2f35-8f5a-4116-a834-e35f310d0d3e](https://user-images.githubusercontent.com/5038584/37950933-88de0cd2-31d5-11e8-8706-62e0ed024acc.png) |

---------------

* [x] SP /introduction

![1fb0cd8e-4023-4a8a-934c-f21b1b277f76](https://user-images.githubusercontent.com/5038584/37949061-f35339aa-31cd-11e8-93ff-4140cefeb5b2.png)

---------------

* [ ] SP /point

|  |  |  | | |
|-|-|-|-|-|
| ![156e5ce0-9e13-48a1-9000-f9b176c3c592](https://user-images.githubusercontent.com/5038584/37949754-e48c845a-31d0-11e8-9459-eda553143c1b.png) | ![0f0e3c6b-1c66-438f-b745-7d70ceb80d0f](https://user-images.githubusercontent.com/5038584/37949756-e4b971f4-31d0-11e8-8636-e43ab451e5a1.png) | ![8d4f260d-ece8-4d40-89c8-b131aaf88e11](https://user-images.githubusercontent.com/5038584/37949757-e4e84088-31d0-11e8-9235-d57e988b03be.png) | ![ff64054d-08c0-4af6-956e-06d75de8a50a](https://user-images.githubusercontent.com/5038584/37949758-e5118d08-31d0-11e8-9979-24de4e145b01.png) | ![f80f647d-9270-491b-b364-6f41c7cedb2e](https://user-images.githubusercontent.com/5038584/37949759-e551a10e-31d0-11e8-8988-0de5974bb1ca.png) |

---------------

* [x] PC,TB /point/**** (menu)

![bae91860-fbd8-40d6-a91c-3d8bdfd40a07](https://user-images.githubusercontent.com/5038584/37949398-6ba44916-31cf-11e8-8d87-327d25109f20.png)

---------------

* [ ] SP, TB /point/******/ (all /point pages should have margin on the section below)

![85db88cd-cab1-4629-80a6-d4c8709ff2dd](https://user-images.githubusercontent.com/5038584/37949973-d8dfb55e-31d1-11e8-9f63-ed9aafc5cb5a.png)

---------------

* [x] PC, SP, TB /point/****/ (set links)

|  |  |
|-|-|
| ![ae0931c5-21bf-4322-b804-b47b5b3e5fc3](https://user-images.githubusercontent.com/5038584/37950684-7d4386fa-31d4-11e8-9b1d-8e3ab1e2d925.png) | ![1d383f49-abb6-4ca8-bb8b-6082ecad579a](https://user-images.githubusercontent.com/5038584/37950790-e3c68c88-31d4-11e8-8f70-81048dd62cea.png) |

---------------

## 3. Due date

(optional)

## 4. Note

(optional)
