### ISSUE TITLE
Checklist #2

### ISSUE THREAD

**Issue by louierosero-gss** [louierosero-gss/Uluru-QA#2]
## 1. Specification / Bug

commit by each tasks below

* [ ] replace background images of service cards on top pages, I've shared images with your boss's dropbox, named "service_photo"
* [ ] remove trailing slash by default (e.g. ```/company/vision/ ``` should be ```/company/vision````)
    * ignore my orders on screen shots below, I indicated some urls with trailing slash
* [ ] make the sidebar-menu item activated when you on the page
    * on ```/company/topmessage``` or ```/service/data_collection```, the menu item on the sidebar is activated
    * but not other pages (e.g. /point/strategy, /service/type/it, /case/case_type/case_it)
    * make them behave like ```/company/topmessage```
* [ ] replace "Kamimage" -> "KAMIMAGE" all

## 2. Screen shot

* [x]  iPad top page
    * [ ] wider header menu

| fix me | ok  | ok  | ok |
|-|-|-|-|
| ![4dc67550-edf2-4f5b-828b-56cd2429efd1](https://user-images.githubusercontent.com/5038584/37948383-ea7554ce-31ca-11e8-9952-aba857aa02e0.png)|![d638e967-4b24-41c6-b544-fc08b9b7b290](https://user-images.githubusercontent.com/5038584/37949189-8860b838-31ce-11e8-9926-fc837551cf48.png)|![592773f1-e4ea-4337-bc11-e59a4c61e322](https://user-images.githubusercontent.com/5038584/37948440-4886cd5e-31cb-11e8-80cf-2f0d9d2325d0.jpeg)|![ff1210e5-2587-43c6-a60e-2f3e5cfa6f43](https://user-images.githubusercontent.com/5038584/37948441-48b37caa-31cb-11e8-8109-8dcc84e60d9f.jpeg)|

---------------

* [ ] SP /point

|  |  |  | | |
|-|-|-|-|-|
| ![156e5ce0-9e13-48a1-9000-f9b176c3c592](https://user-images.githubusercontent.com/5038584/37949754-e48c845a-31d0-11e8-9459-eda553143c1b.png) | ![0f0e3c6b-1c66-438f-b745-7d70ceb80d0f](https://user-images.githubusercontent.com/5038584/37949756-e4b971f4-31d0-11e8-8636-e43ab451e5a1.png) | ![8d4f260d-ece8-4d40-89c8-b131aaf88e11](https://user-images.githubusercontent.com/5038584/37949757-e4e84088-31d0-11e8-9235-d57e988b03be.png) | ![ff64054d-08c0-4af6-956e-06d75de8a50a](https://user-images.githubusercontent.com/5038584/37949758-e5118d08-31d0-11e8-9979-24de4e145b01.png) | ![f80f647d-9270-491b-b364-6f41c7cedb2e](https://user-images.githubusercontent.com/5038584/37949759-e551a10e-31d0-11e8-8988-0de5974bb1ca.png) |

---------------

* [ ] SP, TB /point/******/ (all /point pages should have margin on the section below)

![85db88cd-cab1-4629-80a6-d4c8709ff2dd](https://user-images.githubusercontent.com/5038584/37949973-d8dfb55e-31d1-11e8-9f63-ed9aafc5cb5a.png)

---------------

* [ ] PC,TB,SP top page

![d109fb55-16c7-45cc-b351-465775cd1a11](https://user-images.githubusercontent.com/5038584/37985478-d1888350-3233-11e8-9507-dde29fdbd9ab.png)

---------------

* [ ] SP /company/

![d16a872e-5a49-44b0-a769-75235a1a1e45](https://user-images.githubusercontent.com/5038584/37985706-7e0d70e0-3234-11e8-8535-9a28670ad1ff.png)

---------------

* [ ] /company/about/

![9983bf67-a746-441f-b421-c080da7cae51](https://user-images.githubusercontent.com/5038584/37986930-d665442c-3237-11e8-9ca8-44acd9d76fa0.png)

---------------

* [ ] /company/vision/

![a9b55b2c-5697-4b29-902f-b450ec760743](https://user-images.githubusercontent.com/5038584/37986385-43baa744-3236-11e8-8d40-99a0232cacdc.png)

---------------

* [ ] /company/map/

![f3f62aa8-0706-429d-9adf-1fc63187f84f](https://user-images.githubusercontent.com/5038584/37987314-c868848c-3238-11e8-82e1-21b62a7039ac.png)

pin on the map below

https://goo.gl/maps/YMXFsTzHvi82

---------------

* [ ] /number/

![238e3582-cafb-4627-aa2e-58b2763fc5ba](https://user-images.githubusercontent.com/5038584/37987862-5b2e9756-323a-11e8-98bd-321ccd59ec81.jpeg)

many incorrect titles and texts, take a look back PSD carefully and fix all

---------------

* [ ] /case/

![f504eb07-1ddb-4a07-8c29-bf5b48167492](https://user-images.githubusercontent.com/5038584/37988121-03232eea-323b-11e8-8fcc-f64b2dc6e47c.png)

many incorrect titles, double check and fix all

---------------

* [ ] /case/****/ (detail)

| | |
|-|-|
| ![b10298a2-fcf1-4a84-9111-7ca7502eb914](https://user-images.githubusercontent.com/5038584/37988452-e9c9a75c-323b-11e8-8f84-1a1b93b595a1.png) | ![aed0597f-0030-4dcd-b08b-e4ef28aea17c](https://user-images.githubusercontent.com/5038584/37988451-e99337a8-323b-11e8-868f-cfc240cad990.png) |

set link to bottom button for all case-detail pages

---------------

* [ ] /service/****/ (detail)

![bdf79ab7-3035-4a56-a8cd-207ac8e45ef0](https://user-images.githubusercontent.com/5038584/37989102-7a83c70e-323d-11e8-9a80-04668514a7d3.png)

same problem

* /service/image
* /service/rendering
* /service/kamimage
* /service/image

we have contents on the url lists, but those pages below does not have them yet, put them all

* /service/data_cleansing
* /service/investigation
* /service/writing
* /service/work
* /service/system
* /service/tape
* /service/design
* /service/consulting
* /service/web_marketing

---------------

## 3. Due date

(optional)

## 4. Note

(optional)
